### PR TITLE
@MongoId and @MongoObjectId test coverage improvements.

### LINKED ISSUE #272: ObjectIds in MixIns not working with Jongo 1.2
Fields that get `@MongoId` and `@MongoObjectId` from MixIns are not being used.

### PR DESCRIPTION
**Pull request by ctrimble**
In Jongo 1.2, `@MongoId` and `@MongoObjectId` only work under a few specific conditions.  This PR aims to make `@MongoId` and `@MongoObjectId` more general, using a parameterized test (`org.jongo.marshall.jackson.IdSpecTest`).

### Goal

Get all of the following to be generally true:

- If Jackson sees a property named `_id`, that is the id property for Mongo.
- If Jackson sees `@MongoId`on a property, that property is named `_id` according to Jackson.
- If Jackson sees `@MongoObjectId` on a property, that property is serialized as an `ObjectId`.
- `@MongoId` and `@MongoObjectId` will not alter other `ObjectMapper` instances that see them.

### What has changed

- Reflection is no longer used to inspect instances for the `_id` property and its value.  Instead, Jackson's view of the type is used to determine the property's value and type in Mongo.  The implementation can be found in `org.jongo.marshall.jackson.JacksonObjectIdUpdater`.
- The Serializer and Deserializer were widened, so that property/annotation combinations like `public @MongoObjectId ObjectId _id;` will just no op.
- The *@*MongoId and *@*MongoObjectId annotations are no longer AnnotationBundles, as these were not getting applied for MixIns.  This functionality is now supported directly by `org.jongo.marshall.jackson.JongoAnnotationIntrospector`.
- JUnit rules `org.jongo.util.JongoEmbeddedRule` and `org.jongo.util.MongoEmbeddedRule` have been introduced with the same functionality as `JongoTestCase`.
- Several other tests were added to the test suite dealing with IDs and MixIns.

Fixes #272

### CODE REVIEW

**Comment by ctrimble** [comment]
@bguerout this PR still needs to be squashed, but it should be in good enough shape for review.

File: src/main/java/org/jongo/marshall/jackson/JacksonObjectIdUpdater.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+import org.jongo.marshall.jackson.oid.MongoObjectId;
+
+import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
+import com.fasterxml.jackson.databind.introspect.BasicBeanDescription;
+import com.fasterxml.jackson.databind.introspect.BasicClassIntrospector;
+import com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition;
+import com.fasterxml.jackson.databind.ObjectMapper;
+
+@SuppressWarnings("deprecation")
+public class JacksonObjectIdUpdater implements ObjectIdUpdater {
```
Comment (ctrimble) [inline src/main/java/org/jongo/marshall/jackson/JacksonObjectIdUpdater.java]: Needs an author tag

File: src/test/java/org/jongo/marshall/jackson/IdSpecTest.java [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+import org.jongo.MongoCursor;
+import org.jongo.util.JongoEmbeddedRule;
+import org.jongo.util.MongoEmbeddedRule;
+
+import static org.jongo.model.IdSpecSet.*;
+import static org.hamcrest.CoreMatchers.*;
+import static org.junit.Assert.*;
+
+@RunWith(Parameterized.class)
+public class IdSpecTest {
```
Comment (ctrimble) [inline src/test/java/org/jongo/marshall/jackson/IdSpecTest.java]: Needs an author tag.

File: src/test/java/org/jongo/model/ExternalType.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+import org.jongo.marshall.jackson.oid.MongoObjectId;
+import org.jongo.marshall.jackson.oid.ObjectId;
+
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+/**
+ * Models a type coming from a third party tool like JsonSchema2Pojo.
+ */
+@SuppressWarnings("deprecation")
+public class ExternalType {
```
Comment (ctrimble) [inline src/test/java/org/jongo/model/ExternalType.java]: Needs an author tag.

File: src/test/java/org/jongo/util/JongoEmbeddedRule.java [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+import org.junit.rules.TestRule;
+import org.junit.runner.Description;
+import org.junit.runners.model.Statement;
+
+import com.fasterxml.jackson.databind.ObjectMapper;
+import com.google.common.collect.Sets;
+import com.mongodb.CommandResult;
+import com.mongodb.DB;
+
+public class JongoEmbeddedRule implements TestRule {
```
Comment (ctrimble) [inline src/test/java/org/jongo/util/JongoEmbeddedRule.java]: Needs an author tag and reference to the JongoTestCase.

File: src/test/java/org/jongo/util/MongoEmbeddedRule.java [hunk 5]
```diff
@@ -0,0 +1,23 @@
+package org.jongo.util;
+
+import org.junit.rules.TestRule;
+import org.junit.runner.Description;
+import org.junit.runners.model.Statement;
+
+public class MongoEmbeddedRule implements TestRule {
```
Comment (ctrimble) [inline src/test/java/org/jongo/util/MongoEmbeddedRule.java]: Needs an author tag and a reference to the JongoTestCase.

**Comment by ctrimble** [comment]
@bguerout If these changes look good as is, give me one more day to clean up the few issues I am aware of (author annotations and formatting) and I will squash this into a clean commit.

**Comment by ctrimble** [comment]
Be aware, the way I structured this PR is confusing.  There are relevant notes on #273 that are not showing up here.

**Comment by ctrimble** [comment]
Not sure why, but it looks like the project previously had an embedded mongo rule and it was converted into a subclass of JongoTestCase.  No clue why.  https://github.com/bguerout/jongo/commit/4184d320f255e5e552a76a7e935938b9f7958839

**Comment by ctrimble** [comment]
The way that `MongoId` and `MongoObjectId` are handled in this project may not be the best.  Jackson's [BeanSerializationModifier](https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/ser/BeanSerializerModifier.html) and [BeanDeserializationModifier](https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/deser/BeanDeserializerModifier.html) are better for tasks like this.

**Comment by ctrimble** [comment]
@bguerout I have implemented all of your notes and squashed this into a single commit.  I believe it is now complete.

File: src/test/java/org/jongo/AggregateTest.java [hunk 6]
```diff
@@ -37,6 +45,16 @@
 
 
     private MongoCollection collection;
+    private MongoCollection friendCollection;
+    private MongoCollection externalTypeCollection;
+    
+    @SuppressWarnings("serial")
+    public AggregateTest() {
```
Comment (bguerout) [inline src/test/java/org/jongo/AggregateTest.java]: May be we can regroup mixins tests from SaveTest and AggregateTest into a dedicated MixinsTest

**Comment by bguerout** [comment]
Thanks for the great work

**Comment by ctrimble** [comment]
Thanks for the great project!

**Comment by bguerout** [comment]
This fix can be tested in an early version.
**This version must be considered as a SNAPSHOT of future 1.3 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.3-early-20151113-0140</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```
